# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  displayName: 'Clean build sources folder (pulled from fake git) '
  inputs:
    script: |
      rd /S /Q "$(Build.SourcesDirectory)\.git"
      del /S /Q "$(Build.SourcesDirectory)\*"
      exit
 
- task: CmdLine@2
  displayName: 'Custom git clone'
  inputs:
    script: |
      echo 'Cloning into sources folder at: $(Build.SourcesDirectory)'
      git clone https://$(external-git-user):$(external-git-password)@git.myserver.com/my-repository/my-app.git --progress --branch dev --single-branch --depth=1 $(Build.SourcesDirectory)
      exit